foodticket/foodticket/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('home.urls')),
    path("clientes/", include('clientes.urls')),
    path("menus/", include('menus.urls')),
    path("restaurantes/", include('restaurantes.urls')),
    path("pedidos/", include('pedidos.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

foodticket/home/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "home"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("registrarse/", views.registrarse, name="registrarse"),
    path("cerrar_sesion/", views.cerrar_sesion, name="cerrar_sesion"),
    path("login/", views.iniciar_sesion, name="login"),
]

foodticket/pedidos/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "pedidos"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("historial/", views.Historial, name="historial"),
]

foodticket/pedidos/models.py
from django.db import models
from django.utils import timezone
from restaurantes.models import RestauranteUsuario
from clientes.models import Cliente
from menus.models import Menu


# Create your models here.
class Pedido(models.Model):
    fecha = models.DateTimeField(default=timezone.now)

    id_cliente = models.ForeignKey(Cliente, on_delete=models.SET_NULL, null=True)
    id_restaurante = models.ForeignKey(RestauranteUsuario, on_delete=models.CASCADE)
    menus_comprados = models.ManyToManyField(Menu, through='MenuPedido')


class MenuPedido(models.Model):
    id_pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    id_menu = models.ForeignKey(Menu, on_delete=models.CASCADE)
    cantidad = models.IntegerField(default=1)

foodticket/pedidos/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.decorators import login_required
from .models import Pedido, MenuPedido
from restaurantes.models import RestauranteUsuario
# Create your views here.

# Para crear la primera vista del home
class IndexView(generic.TemplateView):
    template_name = "pedidos/index.html"


@login_required
def Historial(request):
    """Vista para la revisión del historial de pedidos"""
    # TODO: Implementar vista para el historial de pedidos
    restaurante = RestauranteUsuario.objects.get(usuario=request.user)
    pedidos = Pedido.objects.prefetch_related('menupedido_set__id_menu').filter(id_restaurante=restaurante).order_by('-fecha')
    return render(request, "pedidos/historial.html", {"pedidos": pedidos})


# TODO: Implementar vista para la revisión de pedidos pendientes en caso de que se llegue a necesitar o una vista
# para revisar el historial de tiqueteras compradas

foodticket/pedidos/templates/pedidos/historial.html
{% extends 'home/base.html' %}
{% load static %}

{% block content %}
<main>
    <div class="container mt-5">
        <div class="mt-3">
            <h1>Historial</h1>
            <table class="table table-bordered border-warning mt-3">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Fecha</th>
                        <th scope="col">Menu</th>
                        <th scope="col">Cantidad</th>
                        <th scope="col">cliente</th>
                    </tr>
                </thead>
                <tbody>
                    {% for pedido in pedidos %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ pedido.fecha }}</td>
                        <td>
                            <ul class="list-group list-group-flush">
                                {% for menu_pedido in pedido.menupedido_set.all %}
                                    <li class="list-group-item">{{ menu_pedido.id_menu.nombre }}</li>
                                {% endfor %}
                            </ul>
                        </td>
                        <td>
                            <ul class="list-group list-group-flush">
                                {% for menu_pedido in pedido.menupedido_set.all %}
                                    <li class="list-group-item">{{ menu_pedido.cantidad }}</li>
                                {% endfor %}
                            </ul>
                        <td>{{ pedido.id_cliente.cedula }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</main>
{% endblock  %}

foodticket/pedidos/templates/pedidos/index.html
{% extends 'home/base.html' %}
{% load static %}

{% block content %}
<main>
    <div class="container mt-5">
        <h1>Pedidos</h1>
        <a href="{% url 'pedidos:historial' %}" class="btn btn-lg btn-outline-warning mt-3">Historial</a>
    </div>
</main>
{% endblock  %}