foodticket/clientes/urls.py
from django.urls import path
from . import views

app_name = "clientes"
urlpatterns = [
    path('', views.index, name="index"),
    path('compra/', views.compra, name="compra"),
    path('compra/<int:cliente_id>/tiqueteras/', views.seleccionar_tiquetera, name='seleccionar_tiquetera'),
    path('compra/<int:cliente_id>/menus/', views.seleccionar_menu, name='seleccionar_menu'),
    path('venta/', views.venta, name="venta"),
    path('compra/informacion_cliente/', views.informacion_cliente, name='informacion_cliente'),

]

foodticket/foodticket/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('home.urls')),
    path("clientes/", include('clientes.urls')),
    path("menus/", include('menus.urls')),
    path("restaurantes/", include('restaurantes.urls')),
    path("pedidos/", include('pedidos.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

foodticket/home/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "home"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("registrarse/", views.registrarse, name="registrarse"),
    path("cerrar_sesion/", views.cerrar_sesion, name="cerrar_sesion"),
    path("login/", views.iniciar_sesion, name="login"),
]

foodticket/menus/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "menus"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("crear/", views.crear_menu, name="crear_menu"),
    path("<int:menu_id>/eliminar", views.eliminar_menu, name="eliminar_menu"),
    path("<int:menu_id>/editar", views.editar_menu, name="editar_menu"),
] 

foodticket/pedidos/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "pedidos"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("historial/", views.Historial, name="historial"),
]

foodticket/restaurantes/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "restaurantes"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("crear/tiquetera/", views.crear_tiquetera, name="crear_tiquetera"),
]

foodticket/home/models.py
from django.db import models

# Create your models here.

foodticket/home/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.db import IntegrityError

from  restaurantes.models import RestauranteUsuario

# Create your views here.

# Para crear la primera vista del home
class IndexView(generic.TemplateView):
    template_name = "home/index.html"


# Para crear la vista de registro
def registrarse(request):
    """Esta view se encarga de registrar un usuario y un restaurante asociado a ese usuario"""

    if request.method == "GET":
        return render(request, "home/registrarse.html")
    else:
        if request.POST["password1"] == request.POST["password2"]:
            try:                            
                # Creamos el usuario
                username = request.POST["username"]
                password = request.POST["password1"]
                email = request.POST["correo"]
                user = User.objects.create_user(username=username, password=password, email=email)
                user.save()

                # Logeamos al usuario creando la sesión
                login(request, user)

                # Creamos el restaurante de ese usuario
                nombre_restaurante = request.POST["nombre_restaurante"]
                nit_restaurante = request.POST["nit_restaurante"]
                direccion_restaurante = request.POST["direccion_restaurante"]
                telefono_restaurante = request.POST["telefono_restaurante"]
                tipo_restaurante = request.POST["tipo_restaurante"]
                restaurante = RestauranteUsuario.objects.create(nombre=nombre_restaurante, NIT=nit_restaurante, direccion=direccion_restaurante, telefono=telefono_restaurante, tipo=tipo_restaurante, usuario=user)
                restaurante.save()
                return redirect("restaurantes:index")
            
            except IntegrityError:
                return render(request, "home/registrarse.html", {"error": "El nombre de usuario ya existe"})
        else:
            return render(request, "home/registrarse.html", {"error": "Las contraseñas no coinciden"})


def cerrar_sesion(request):
    """Esta view se encarga de cerrar la sesión del usuario y redireccionar a la página de inicio"""
    logout(request)
    return redirect("home:index")


def iniciar_sesion(request):
    """Esta view se encarga de iniciar la sesión del usuario y redireccionar a la página de inicio"""
    if request.method == "GET":
        return render(request, "home/login.html")
    else:
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Comprobamos si el usuario existe, o sea si el usuario y la contraseña son correctos
        if user is not None:
            login(request, user)
            return redirect("restaurantes:index")
        else:
            return render(request, "home/login.html", {"error": "El usuario o la contraseña son incorrectos"})

foodticket/home/templates/home/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'home/css/style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;800&display=swap" rel="stylesheet">
    <style>
        .form-input {
            width: 200px;
            padding:5px;
            border-radius:5px;
        }
    </style>
    <title>FoodTicket</title>
</head>
<body>
    <header>
        <nav class="nav-sidebar">
            <div class="nav-sidebar__logo">
                <a href="/">
                    <figure >
                        <img src="{% static 'home/images/logo.png' %}" alt="Logo FoodTicket">
                    </figure>
                </a>
            </div>
            <ul class="nav-sidebar__menu">
                <li class="nav-sidebar__menu__item">
                    <a href="{% url 'home:index' %}" class="nav-sidebar__menu__item__link">
                        <figure>
                            <img src="{% static 'home/images/home.png' %}" alt="Icono casa" width=30 height=30>
                        </figure>
                        <p>Home</p>
                    </a>
                </li>
                <li class="nav-sidebar__menu__item">
                    <a href="{% url 'clientes:index' %}" class="nav-sidebar__menu__item__link">
                        <figure>
                            <img src="{% static 'home/images/clientes.png' %}" alt="Icono casa" width=30 height=30>
                        </figure>
                        <p>Clientes</p>
                    </a>
                </li>
                <li class="nav-sidebar__menu__item">
                    <a href="{% url 'menus:index' %}" class="nav-sidebar__menu__item__link">
                        <figure>
                            <img src="{% static 'home/images/menus.png' %}" alt="Icono casa" width=30 height=30>
                        </figure>
                        <p>Menús</p>
                    </a>
                </li>
                <li class="nav-sidebar__menu__item">
                    <a href="{% url 'restaurantes:index' %}" class="nav-sidebar__menu__item__link">
                        <figure>
                            <img src="{% static 'home/images/restaurante.png' %}" alt="Icono casa" width=30 height=30>
                        </figure>
                        <p>Restaurante</p>
                    </a>
                <li class="nav-sidebar__menu__item">
                    <a href="{% url 'pedidos:index' %}" class="nav-sidebar__menu__item__link">
                        <figure>
                            <img src="{% static 'home/images/pedidos.png' %}" alt="Icono casa" width=30 height=30>
                        </figure>
                        <p>Pedidos</p>
                    </a>
                </li>

            </ul>
            <ul class="nav-sidebar__login">
                {% if user.is_authenticated %}
                <li class="nav-sidebar__menu__item">
                    <a href="{% url 'home:cerrar_sesion' %}" class="nav-sidebar__menu__item__link">
                        <figure>
                            <img src="{% static 'home/images/logout.png' %}" alt="Icono casa" width=30 height=30>
                        </figure>
                        <p>Logout</p>
                    </a>
                </li>
                {% else %}
                <li class="nav-sidebar__menu__item">
                    <a href="{% url 'home:login' %}" class="nav-sidebar__menu__item__link">
                        <figure>
                            <img src="{% static 'home/images/login.png' %}" alt="Icono casa" width=30 height=30>
                        </figure>
                        <p>Login</p>
                    </a>
                </li>
                <li class="nav-sidebar__menu__item">
                    <a href="{% url 'home:registrarse' %}" class="nav-sidebar__menu__item__link">
                        <figure>
                            <img src="{% static 'home/images/registrarse.png' %}" alt="Icono casa" width=30 height=30>
                        </figure>
                        <p>Registrarse</p>
                    </a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </header>

    {% block content %}
    {% endblock  %}

</body>
</html>

foodticket/home/templates/home/index.html
{% extends 'home/base.html' %}
{% load static %}
{% block content %}
<main>
    <div class="principal">
        <div class="principal__texto">
            <h1>Bienvenido a FoodTicket</h1>
            <p>Tu asistente para restaurante</p>
        </div>
        <div class="principal__imagen">
            <figure>
                <img src="{% static 'home/images/principal_icon.png' %}" alt="Icono plato">
            </figure>
        </div>
    </div>
</main>
{% endblock  %}

foodticket/home/templates/home/login.html
{% extends 'home/base.html' %}
{% load static %}

{% block content %}
<main>
    <div class="container mt-5">
        <div class="col-md-5 offset-md-4">
            <div class="row">
                <h1>Iniciar Sesión</h1>
                <p>{{ error }}</p>          
                <form action={% url 'home:login' %} method="POST" class="card card-body">
                    {% csrf_token %}
                    <div class="mb-1">
                        <label for="username" class="form-label">Usuario:</label>
                        <input type="text" name="username" id="username" class="form-control" placeholder="Nombre de usuario" required>
                    </div>
                    <div class="mb-1">
                        <label for="password" class="form-label">Contraseña:</label>
                        <input type="password" name="password" id="password" class="form-control" placeholder="Contraseña" required>
                    </div>
    
                    <button type="submit" class="btn btn-outline-warning mt-2">Login</button>
                    
                </form>
            </div>
        </div>
    </div>
</main>
{% endblock %}

foodticket/home/templates/home/registrarse.html
{% extends 'home/base.html' %}
{% load static %}

{% block content %}
<main>
    <div class="container mt-5">
        <div class="col-md-6 offset-md-3">
            <div class="row">
                <h1>Registrarse</h1>
                <p>{{ error }}</p>
                <form action={% url 'home:registrarse' %} method="POST" class="card card-body">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col">
                            <div class="mb-1">
                                <label for="correo" class="form-label">Correo:</label>
                                <input type="text" name="correo" id="correo" class="form-control" placeholder="ejemplo@gmail.com" required>
                            </div>
                            <div class="mb-1">
                                <label for="username" class="form-label">Usuario:</label>
                                <input type="text" name="username" id="username" class="form-control" placeholder="Nombre de usuario" required>
                            </div>
                            <div class="mb-1">
                                <label for="nombre_restaurante" class="form-label">Nombre del restaurante:</label>
                                <input type="text" name="nombre_restaurante" id="nombre_restaurante" class="form-control"
                                placeholder="Nombre restaurante" required>
                            </div>
                            <div class="mb-1">
                                <label for="password1" class="form-label">Contraseña:</label>
                                <input type="password" name="password1" id="password1" class="form-control" placeholder="Contraseña" required>
                            </div>
                            <div class="mb-1">
                                <label for="password2" class="form-label">Confirmar contraseña:</label>
                                <input type="password" name="password2" id="password2" class="form-control" placeholder="Confirmar contraseña" required>
                            </div>
                            <button type="submit" class="btn btn-outline-warning mt-4">Registrarse</button>
                        </div>
    
                        <div class="col">
                            <div class="mb-1">
                                <label for="nit_restaurante" class="form-label">NIT:</label>
                                <input type="text" name="nit_restaurante" id="nit_restaurante" class="form-control"
                                placeholder="NIT restaurante">
                            </div>
                            <div class="mb-1">
                                <label for="direccion_restaurante" class="form-label">Dirección:</label>
                                <input type="text" name="direccion_restaurante" id="direccion_restaurante" class="form-control"
                                placeholder="Direccion restaurante" required>
                            </div>
                            <div class="mb-1">
                                <label for="telefono_restaurante" class="form-label">Teléfono:</label>
                                <input type="text" name="telefono_restaurante" id="telefono_restaurante" class="form-control"
                                placeholder="Teléfono restaurante" required>
                            </div>
                            <div class="mb-1">
                                <label for="tipo_restaurante" class="form-label">Tipo:</label>
                                <input type="text" name="tipo_restaurante" id="tipo_restaurante" class="form-control"
                                placeholder="Tipo de restaurante">
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</main>
{% endblock %}