foodticket/clientes/urls.py
from django.urls import path
from . import views

app_name = "clientes"
urlpatterns = [
    path('', views.index, name="index"),
    path('compra/', views.compra, name="compra"),
    path('compra/<int:cliente_id>/tiqueteras/', views.seleccionar_tiquetera, name='seleccionar_tiquetera'),
    path('compra/<int:cliente_id>/menus/', views.seleccionar_menu, name='seleccionar_menu'),
    path('venta/', views.venta, name="venta"),
    path('compra/informacion_cliente/', views.informacion_cliente, name='informacion_cliente'),

]

foodticket/foodticket/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('home.urls')),
    path("clientes/", include('clientes.urls')),
    path("menus/", include('menus.urls')),
    path("restaurantes/", include('restaurantes.urls')),
    path("pedidos/", include('pedidos.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

foodticket/home/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "home"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("registrarse/", views.registrarse, name="registrarse"),
    path("cerrar_sesion/", views.cerrar_sesion, name="cerrar_sesion"),
    path("login/", views.iniciar_sesion, name="login"),
]

foodticket/clientes/models.py
from django.db import models
from restaurantes.models import RestauranteUsuario

# Create your models here.
class Cliente(models.Model):
    nombre = models.CharField(max_length=100)
    cedula = models.CharField(max_length=20, unique=True)


class Tiquetera(models.Model):
    cantidad = models.IntegerField(default=0)
    redimidos = models.IntegerField(default=0)
    id_restaurante = models.ForeignKey(RestauranteUsuario, on_delete=models.CASCADE)
    id_cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)

foodticket/clientes/forms.py
from django import forms
from .models import Cliente, Tiquetera
class FormularioVentaTiquetera(forms.Form):
    nombre = forms.CharField(label="Nombre", widget=forms.TextInput(attrs={"class": "form-control"}))
    cedula = forms.CharField(label="Cedula", widget=forms.TextInput(attrs={"class": "form-control", "required": True}))
    

class FormularioVentaAlmuerzo(forms.Form):
    cedula = forms.CharField(label="Cedula", widget=forms.TextInput(attrs={"class": "form-control", "required": True}))


class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ["nombre", "cedula"]
        widgets = {
            "nombre": forms.TextInput(attrs={"class": "form-control", "required": True}),
            "cedula": forms.TextInput(attrs={"class": "form-control", "required": True}),
        }

foodticket/clientes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.db import IntegrityError
from django.core.exceptions import ObjectDoesNotExist
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from .forms import FormularioVentaTiquetera,FormularioVentaAlmuerzo, ClienteForm
from .models import Cliente, Tiquetera
from restaurantes.models import RestauranteUsuario, TiqueteraVenta
from pedidos.models import Pedido, MenuPedido
from menus.models import Menu

# Create your views here.

#TODO: Agregar validaciones de login

def index(request):
    return render(request, "clientes/index.html")


@login_required
def venta(request):

    formulario = FormularioVentaTiquetera()
    restaurante = RestauranteUsuario.objects.get(usuario=request.user)
    tiqueteras_restaurante = TiqueteraVenta.objects.filter(id_restaurante=restaurante)

    if request.method == 'POST':

        formulario = FormularioVentaTiquetera(data=request.POST)
        restaurante = RestauranteUsuario.objects.get(usuario=request.user)

        if formulario.is_valid():
            nombre = request.POST.get("nombre")
            cedula = request.POST.get("cedula")

        # Se guarda la tiquetaera seleccionada
        tiquetera_venta = TiqueteraVenta.objects.get(id=request.POST.get("tiquetera_select"))
        cantidad_tiquetes = tiquetera_venta.cantidad
        # Si el cliente no existe debe crearse
        try:
            cliente = Cliente.objects.create(nombre=nombre, cedula=cedula)
            tiquetera = Tiquetera.objects.create(cantidad=cantidad_tiquetes, id_restaurante=restaurante, id_cliente=cliente)

            # Se debe guardar el cliente y la tiquetera
            cliente.save()
            tiquetera.save()

        # Si el cliente ya existe se debe recuperar para asiganrle la tiquetera
        except IntegrityError:
            cliente = Cliente.objects.get(cedula=cedula)

            tiquetera = Tiquetera.objects.create(cantidad=cantidad_tiquetes, id_restaurante=restaurante, id_cliente=cliente)

            # Se debe guardar la tiquetera

            tiquetera.save()

        return redirect("clientes:index")
    else:
        return render(request, "clientes/venta.html", {
            "formulario_venta": formulario,
            "tiqueteras": tiqueteras_restaurante
            })


@login_required
def compra(request):

    formulario = FormularioVentaAlmuerzo()
    restaurante = RestauranteUsuario.objects.get(usuario=request.user)

    if request.method == 'POST':

        try:
            cliente = Cliente.objects.get(cedula=request.POST.get("cedula"))
            tiqueteras = Tiquetera.objects.filter(id_cliente=cliente, id_restaurante = restaurante)
            if tiqueteras.count() == 0:
                return render(request, "clientes/compra.html",
                            {"error": "El cliente no tiene tiqueteras",
                            "formulario_compra": formulario}
                            )
            return redirect("clientes:seleccionar_tiquetera", cliente_id=cliente.id)

        except ObjectDoesNotExist:
            return render(request, "clientes/compra.html",
                            {"error": "El cliente no tiene tiqueteras",
                            "formulario_compra": formulario}
                            )

    else:
        return render(request, "clientes/compra.html", {"formulario_compra": formulario})


# TODO: Si no se seleccionan menus igual se descuenta la tiquetera, se debe solucionar esto tal vez guardando todo en una misma
# View y en esta solo hacer la verificación si hay tiquetes suficientes o no
@login_required
def seleccionar_tiquetera(request, cliente_id):

    restaurante = RestauranteUsuario.objects.get(usuario=request.user)
    tiqueteras = Tiquetera.objects.filter(id_restaurante = restaurante, id_cliente = cliente_id)
    cliente = Cliente.objects.get(id=cliente_id)

    if request.method == 'POST':
            tiquetera = Tiquetera.objects.get(pk=request.POST.get("tiquetera_select"), id_restaurante = restaurante, id_cliente = cliente)

            # Se debe validar que la cantidad de tiquetes sea suficiente
            if tiquetera.cantidad - tiquetera.redimidos >= int(request.POST.get("cantidad")):
                tiquetera.redimidos += int(request.POST.get("cantidad"))

                # Si se iguala la cantidad de tiquetes a la cantidad de tiquetes redimidos se debe eliminar la tiquetera
                if tiquetera.cantidad == tiquetera.redimidos:
                    tiquetera.delete()
                else:
                    tiquetera.save()
            else:
                return render(request, "clientes/seleccionTiquetera.html",
                            {"error": "No hay suficientes tiquetes para realizar la compra",
                            "tiqueteras": tiqueteras, "cliente": cliente}
                            )

            return render(request, "clientes/seleccionMenu.html",{
                "cliente": cliente, "menus": restaurante.menu_set.all(),
                "cantidad": [i for i in range(int(request.POST.get("cantidad")))]
                })
    else:
        return render(request, "clientes/seleccionTiquetera.html",
                        {"tiqueteras": tiqueteras, "cliente": cliente})


@login_required
def seleccionar_menu(request, cliente_id):

    restaurante = RestauranteUsuario.objects.get(usuario=request.user)
    cliente = Cliente.objects.get(id=cliente_id)
    menus = restaurante.menu_set.all()

    if request.method == 'POST':
        menus_seleccionados = dict(request.POST.items())
        menus_seleccionados.pop("csrfmiddlewaretoken")

        pedido = Pedido.objects.create(id_restaurante=restaurante, fecha=timezone.now(), id_cliente=cliente)

        # Se cuentas las veces que se pide un menu
        cantidad = {}
        for i, menu_id in menus_seleccionados.items():
            cantidad[menu_id] = cantidad.get(menu_id, 0) + 1

        # Se añaden los menus al pedido y su cantidad
        for i in menus_seleccionados:
            menu = Menu.objects.get(pk=menus_seleccionados[i])
            pedido.menus_comprados.add(menu, through_defaults={'cantidad': cantidad[str(menus_seleccionados[i])]})

        pedido.save()

        return redirect("clientes:index")
    else:
        return render(request, "clientes/seleccionMenu.html",
                        {"menus": menus, "cliente": cliente})


# TODO: Al momento de vender tiqueteras sería conveniente vernder una cantidad especifica y no x cantidad
# Tal vez reemplazar este modo de compra perimitiendo seleccionar la tiquetera previamente creada por el restaurante
# TODO: Si se implementa lo anterior crear la view para crear tiqueteras
# TODO: Implementar la funcionalidad para que el cliente pueda ver sus tiqueteras
# TODO: Implementar la funcionalidad para dar almuerzos gratis por una cantidad de tiqueteras redimidas si el restaurante lo desea

def informacion_cliente(request, cliente_id):

    formulario = FormularioVentaAlmuerzo()
    restaurante = RestauranteUsuario.objects.get(usuario=request.user)

    if request.method == 'POST':

        try:
            cliente = Cliente.objects.get(cedula=request.POST.get("cedula"))
            tiqueteras = Tiquetera.objects.filter(id_cliente=cliente, id_restaurante = restaurante)
            if tiqueteras.count() == 0:
                return render(request, "clientes/compra.html",
                            {"error": "El cliente no tiene tiqueteras",
                            "formulario_compra": formulario}
                            )
            return redirect("clientes:seleccionar_tiquetera", cliente_id=cliente.id)

        except ObjectDoesNotExist:
            return render(request, "clientes/compra.html",
                            {"error": "El cliente no tiene tiqueteras",
                            "formulario_compra": formulario}
                            )

    else:
        return render(request, "clientes/compra.html", {"formulario_compra": formulario})







    """restaurante = RestauranteUsuario.objects.get(usuario=request.user)
    tiqueteras = Tiquetera.objects.filter(id_restaurante = restaurante, id_cliente = cliente_id)
    cliente = Cliente.objects.get(id=cliente_id)

    if request.method == 'POST':
            tiquetera = Tiquetera.objects.get(pk=request.POST.get("tiquetera_select"), id_restaurante = restaurante, id_cliente = cliente)

            # Se debe validar que la cantidad de tiquetes sea suficiente
            if tiquetera.cantidad - tiquetera.redimidos >= int(request.POST.get("cantidad")):
                tiquetera.redimidos += int(request.POST.get("cantidad"))

                # Si se iguala la cantidad de tiquetes a la cantidad de tiquetes redimidos se debe eliminar la tiquetera
                if tiquetera.cantidad == tiquetera.redimidos:
                    tiquetera.delete()
                else:
                    tiquetera.save()
            else:
                return render(request, "clientes/seleccionTiquetera.html",
                            {"error": "No hay suficientes tiquetes para realizar la compra",
                            "tiqueteras": tiqueteras, "cliente": cliente}
                            )

            return render(request, "clientes/seleccionMenu.html",{
                "cliente": cliente, "menus": restaurante.menu_set.all(),
                "cantidad": [i for i in range(int(request.POST.get("cantidad")))]
                })
    else:
        return render(request, "clientes/seleccionTiquetera.html",
                        {"tiqueteras": tiqueteras, "cliente": cliente})"""

foodticket/clientes/templates/clientes/compra.html
{% extends 'clientes/index.html' %}

{% load static %}

{% block content_clientes %}

    <div class="container mt-2">
        {{ error }}
        <div class="col-md-4 offset-md-3 mt-5">
            <form action="{% url 'clientes:compra' %}" method="POST" class="card card-body">
                {% csrf_token %}
                {{formulario_compra.as_p}}
                <input type="submit" value="Seleccionar" class="btn btn-lg btn-outline-warning mt-3 me-2">
            </form>
        </div>
    </div>

{% endblock  %}

foodticket/clientes/templates/clientes/index.html
{% extends 'home/base.html' %}
{% load static %}

{% block content %}
<main>
    {% if request.user.is_authenticated %}
        <div class="container mt-5">
            <div class="mt-5">
                <h1>Clientes</h1>
                <a href="{% url 'clientes:compra' %}" class="btn btn-lg btn-outline-warning mt-3 me-2">Vender almuerzo</a>
                <a href="{% url 'clientes:venta' %}" class="btn btn-lg btn-outline-warning mt-3 me-2">Vender tiquetera </a>

                {% block content_clientes %}
                {% endblock  %}
            </div>
        </div>
    {% else %}
        <div class="container mt-5">
            <div class="mt-5">
                <h1>Clientes</h1>

                <form action="{% url 'clientes:informacion_cliente' %}" method="POST" class="card card-body">
                    {% csrf_token %}
                    {{formulario_compra.as_p}}
                    <input type="submit" value="Seleccionar" class="btn btn-lg btn-outline-warning mt-3 me-2">
                </form>

            </div>
        </div>
    {% endif %}
</main>
{% endblock content %}

foodticket/clientes/templates/clientes/seleccionMenu.html
{% extends 'clientes/index.html' %}

{% load static %}

{% block content_clientes %}

    <div class="container mt-3">
        {{ error }}
        <h2>Selecciona tus comidas</h2>
        <div class="mt-4">
            {% if cantidad %}
            <form action="{% url 'clientes:seleccionar_menu' cliente.id %}" method="POST"> 
                {% csrf_token %}
                <div class="row row-cols-4 g-4">
                    {% for i in cantidad %}
                        <div class="col">
                            <select name="menu_{{ i }}" id="menu_{{ i }}" class="form-select form-select-lg">
                                {% for menu in menus %}
                                    <option value="{{ menu.id }}">{{ menu.nombre }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    {% endfor %}
                </div>

                <button type="submit" class="btn btn-outline-warning mt-4">Seleccionar</button>
            </form>
            {% endif %}
        </div>
    </div>

{% endblock  %}

foodticket/clientes/templates/clientes/seleccionTiquetera.html
{% extends 'clientes/index.html' %}

{% load static %}

{% block content_clientes %}
<div class="container mt-5">
    <div class="col-md-6 offset-md-3 mt-5">
        {{error}}
        <form action="{% url 'clientes:seleccionar_tiquetera' cliente.id %}" method="POST" class="card card-body">
        {% csrf_token %}
            <label for="cedula" class="form-label">cedula: </label>
            <input type="text" name="cedula" id="cedula" class="form-control" disabled value={{ cliente.cedula }}>
            <table class="table table-bordered border-warning table-striped table-hover mt-3">
                <thead>
                    <th scope="col">Tiquetera</th>
                    <th scope="col">Tiquetes<br>Totales</th>
                    <th scope="col">Tiquetes<br>Redimidos</th>
                </thead>
                <tbody>
                    {% for tiquetera in tiqueteras %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ tiquetera.cantidad }}</td>
                            <td>{{ tiquetera.redimidos }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            <label for="tiquetera_select" class="form-label">Tiquetera: </label>
            <select name="tiquetera_select" id="tiquetera_select" class="form-select form-select-lg mb-3" required>
                {% for tiquetera in tiqueteras %}
                    <option value="{{tiquetera.id}}">Tiquetera {{ forloop.counter }}</option>
                {% endfor %}
            </select>
            <label for="cantidad" class="form-label">cantidad: </label>
            <input type="number" name="cantidad" id="cantidad" class="form-control" required>

            <button type="submit" class="btn btn-lg btn-outline-warning mt-5">Seleccionar</button>
        </form>
    </div>
</div>

{% endblock  %}

foodticket/clientes/templates/clientes/venta.html
{% extends 'clientes/index.html' %}
{% load static %}

{% block content_clientes %}

    <div class="container mt-2">
        <div class="col-md-4 offset-md-3 mt-5">
            <form action="{% url 'clientes:venta' %}" method="POST" class="card card-body">
                {% csrf_token %}
                {{formulario_venta.as_table}}
                <label for="tiquetera_select" class="form-label">Seleccionar Tiquetera</label>
                <select name="tiquetera_select" id="tiquetera_select" class="form-select form-select-lg mb-3" required>
                    {% for tiquetera in tiqueteras %}
                        <option value="{{tiquetera.id}}">Tiquetera {{ forloop.counter }}</option>
                    {% endfor %}
                </select>
                <input type="submit" value="Comprar" class="btn btn-lg btn-outline-warning mt-3 me-2">
            </form>
        </div>
    </div>
    <div class="container mt-5">
        <div class="row row-cols-5 mt-2 gy-2">
            {% if tiqueteras %}
                    {% for tiquetera in tiqueteras %}
                        <div class="col">
                            <div class="card" style="width: 14rem">
                                <div class="card-body">
                                    <h3 class="card-title text-center">Tiquetera {{ forloop.counter }}</h3>
                                    <h4 class="card-title mt-3 mb-3">Tiquetes: {{ tiquetera.cantidad }}</h4>
                                    <p>Precio: $ {{ tiquetera.precio }}</p>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
            {% else %}
                <p>No hay menús creados</p>
            {% endif %}
        </div>
    </div>
{% endblock  %}