foodticket/foodticket/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('home.urls')),
    path("clientes/", include('clientes.urls')),
    path("menus/", include('menus.urls')),
    path("restaurantes/", include('restaurantes.urls')),
    path("pedidos/", include('pedidos.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

foodticket/home/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "home"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("registrarse/", views.registrarse, name="registrarse"),
    path("cerrar_sesion/", views.cerrar_sesion, name="cerrar_sesion"),
    path("login/", views.iniciar_sesion, name="login"),
]

foodticket/menus/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "menus"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("crear/", views.crear_menu, name="crear_menu"),
    path("<int:menu_id>/eliminar", views.eliminar_menu, name="eliminar_menu"),
    path("<int:menu_id>/editar", views.editar_menu, name="editar_menu"),
] 

foodticket/menus/models.py
from django.db import models
from restaurantes.models import RestauranteUsuario
import os
from django.core.exceptions import ValidationError

def validate_image_extension(value):
    ext = os.path.splitext(value.name)[1]  # Obtener la extensión del archivo
    valid_extensions = ['.png', '.jpg', '.jpeg']
    if not ext.lower() in valid_extensions:
        raise ValidationError('El archivo debe ser un PNG, JPG o JPEG')
    
# Create your models here.
class Menu(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField(blank=True)
    imagen = models.ImageField(upload_to='menu_imagenes', blank=True, null=True, validators=[validate_image_extension])
    lunes = models.BooleanField(default=False)
    martes = models.BooleanField(default=False)
    miercoles = models.BooleanField(default=False)
    jueves = models.BooleanField(default=False)
    viernes = models.BooleanField(default=False)
    sabado = models.BooleanField(default=False)
    domingo = models.BooleanField(default=False)

    id_restaurante = models.ForeignKey(RestauranteUsuario, on_delete=models.CASCADE)

foodticket/menus/forms.py
from django import forms
from .models import Menu

class MenuForm(forms.ModelForm):
    class Meta:
        # Modelo en el cual estará basado el formulario
        model = Menu
        # Campos que se mostrarán en el formulario
        fields = ["nombre", "descripcion", "imagen", "lunes", "martes", "miercoles", "jueves", "viernes", "sabado", "domingo"]
        widgets = {
            "nombre": forms.TextInput(attrs={"class": "form-control mt-1", "required": True}),
            "descripcion": forms.Textarea(attrs={"class": "form-control mt-1", "required": True}),
            "imagen": forms.FileInput(attrs={"class": "form-control mt-1", "required": True}),
            "lunes": forms.CheckboxInput(attrs={"class": "form-check-input"}),
            "martes": forms.CheckboxInput(attrs={"class": "form-check-input"}),
            "miercoles": forms.CheckboxInput(attrs={"class": "form-check-input"}),
            "jueves": forms.CheckboxInput(attrs={"class": "form-check-input"}),
            "viernes": forms.CheckboxInput(attrs={"class": "form-check-input"}),
            "sabado": forms.CheckboxInput(attrs={"class": "form-check-input"}),
            "domingo": forms.CheckboxInput(attrs={"class": "form-check-input"}),
        }
        labels = {
            "imagen": "Imagen del menú: *.png",
        }

foodticket/menus/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic
from django.db import IntegrityError
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ValidationError

from .models import Menu
from  restaurantes.models import RestauranteUsuario
from .forms import MenuForm
# Create your views here.

class IndexView(generic.ListView):
    """
    View principal de los menús del restaurante
    
    pasa como contexto los menus del restaurante del usuario que está con la sesión iniciada
    """
    template_name = "menus/index.html"

    context_object_name = "menus_restaurante"

    def get_queryset(self):
        # Si el usuario está autenticado, devolvemos los menús del restaurante del usuario
        if self.request.user.is_authenticated:
            return Menu.objects.filter(id_restaurante__usuario=self.request.user)
    

# TODO: Implementar la lógica para permitir añadir una imagen al menú
@login_required
def crear_menu(request):
    """Crea un menú para el restaurante del usuario que está con la sesión iniciada"""
    if request.method == "GET":
        return render(request, "menus/crear_menu.html", {
            "form": MenuForm
        })
    else:
        try:
            # Llenamos el formulario con los datos ya creado con los datos del POST y los archivos subidos
            form = MenuForm(request.POST, request.FILES)

            # Guardamos los datos como un menu, pero no guardamos en la DB
            menu = form.save(commit=False)
            
            # Asignamos el restaurante del usuario a la variable restaurante
            restaurante = RestauranteUsuario.objects.get(usuario=request.user)

            # Asignamos el restaurante del usuario al menú
            menu.id_restaurante = restaurante

            # Comprobamos si el checkbox de diario está marcado para marcar todos los días
            try:
                if request.POST["diario"] == "on":
                    menu.lunes = True
                    menu.martes = True
                    menu.miercoles = True
                    menu.jueves = True
                    menu.viernes = True
                    menu.sabado = True
                    menu.domingo = True
            except:
                pass
            
            # Guardamos el menú en la base de datos
            menu.save()

            # Redirigimos al usuario a la página de menus
            return redirect("menus:index")
        except IntegrityError:
            return render(request, "menus/crear_menu.html", {
                "error": "Menú ya creado"
            })
        except ValueError:
            return render(request, "menus/crear_menu.html", {
                "error": "Formato no admitido",
                "form": MenuForm
            })


@login_required
def eliminar_menu(request, menu_id):
    """Elimina el menú con el id pasado por parámetro"""
    # Buscamos el menú con el id pasado por parámetro
    menu = get_object_or_404(Menu, id=menu_id)

    # Eliminamos el menú
    menu.delete()

    # Redirigimos al usuario a la página de menus
    return redirect("menus:index")


@login_required
def editar_menu(request, menu_id):
    """Edita el menú con el id pasado por parámetro"""
    # Buscamos el menú con el id pasado por parámetro
    menu = get_object_or_404(Menu, id=menu_id)

    if request.method == "GET":
        return render(request, "menus/editar_menu.html", {
            "form": MenuForm(instance=menu),
            "menu": menu
        })
    else:
        try:
            # Llenamos el formulario con los datos ya creado con los datos del POST
            form = MenuForm(request.POST, instance=menu)

            # Actualizamos el menú en la base de datos
            form.save()

            # Redirigimos al usuario a la página de menus
            return redirect("menus:index")
        except IntegrityError:
            return render(request, "menus/editar_menu.html", {
                "error": "Menú ya creado"
            })

foodticket/menus/templates/menus/crear_menu.html
{% extends 'home/base.html' %}
{% load static %}

{% block content %}
<main>
    <div class="container mt-5">
        <div class="col-md-4 offset-md-3">
            <div class="row">
                <h1>Crea tu Menú</h1>
                <p>{{ error }}</p>
                {% comment "" %} enctype="multipart/form-data" es muy importante ya que nos permite recibir imagenes en el form{% endcomment %}
                <form action="{% url 'menus:crear_menu' %}" method="POST" enctype="multipart/form-data" class="card card-body">
                    {% csrf_token %}
                    <div class='row'>
                        <div>
                            {% for field in form.visible_fields %}
                                {% if field.field.widget.input_type != 'checkbox' %}
                                    <div class="m-2">
                                        <label class="form-check-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
                                        {{ field }}
                                    </div>
                                {% endif %}
                            {% endfor %}
                        </div>
                        <div class="row g-2">
                            {% for field in form.visible_fields %}
                                    {% if field.field.widget.input_type == 'checkbox' %}
                                        <div class="col-5 m-2">
                                            {{ field }}
                                            <label class="form-check-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
                                        </div>
                                    {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                    
                    <div class="mt-1">
                        <label class="form-check-label" for="diario">Diario</label>
                        <input type="checkbox" name="diario" class="form-check-input">
                    </div>
                    
                    <button type="submit" class="btn btn-outline-warning mt-4">Crear</button>
                </form>
            </div>
        </div>
    </div>
</main>
{% endblock  %}

foodticket/menus/templates/menus/editar_menu.html
{% extends 'home/base.html' %}
{% load static %}

{% block content %}
<main>
    <div class="container mt-5">
        <div class="col-md-4 offset-md-3">
            <div class="row">
                <h1>Editar menú</h1>
                <p>{{ error }}</p>
                <form action="{% url 'menus:editar_menu' menu.id %}" method="POST" class="card card-body">
                    {% csrf_token %}
                    <div class='row'>
                        <div>
                            {% for field in form.visible_fields %}
                                {% if field.field.widget.input_type != 'checkbox' %}
                                    <div class="m-2">
                                        <label class="form-check-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
                                        {{ field }}
                                    </div>
                                {% endif %}
                            {% endfor %}
                        </div>
                        <div class="row g-2">
                            {% for field in form.visible_fields %}
                                {% if field.field.widget.input_type == 'checkbox' %}
                                    <div class="col-5 m-2">
                                        {{ field }}
                                        <label class="form-check-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
                                    </div>
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>

                    <button type="submit" class="btn btn-outline-warning mt-4">Guardar</button>
                </form>
                
            </div>
        </div>
    </div>
</main>
{% endblock  %}

foodticket/menus/templates/menus/index.html
{% extends 'home/base.html' %}
{% load static %}

{% block content %}
<main>
    <div class="container mt-5">
        <div class="col-md-6">
            <h1>Tus Menús</h1>
            <a href="{% url 'menus:crear_menu' %}" class="btn btn-lg btn-outline-warning mt-4">
                <span>Crear Menú</span>
            </a>
        </div>
        
        {% if request.user %}
        <div class="row row-cols-4 mt-2 gy-4">
            {% if menus_restaurante %}
                    {% for menu in menus_restaurante %}
                        <div class="col">
                            <div class="card" style="width: 18rem">
                                <img src="{{ MEDIA_URL }}{{ menu.imagen.url }}" class="card-img-top" alt="menu" width="200" height="200">
                                <div class="card-body">
                                    <h5 class="card-title">{{ menu.nombre }}</h5>
                                    <div class="overflow-hidden" style="height: 8rem">
                                        <p class="card-text h-25">{{ menu.descripcion }}</p>
                                    </div>
                                    <div class="row row-cols-4">
                                        <p class="col card-text">L: 
                                            {% if menu.lunes %}
                                                <input class="form-check-input" type="checkbox" checked disabled>
                                            {% else %}
                                                <input class="form-check-input" type="checkbox" disabled>
                                            {% endif %}
                                        </p>
                                        <p class="col card-text">M: 
                                            {% if menu.martes %}
                                                <input class="form-check-input" type="checkbox" checked disabled>
                                            {% else %}
                                                <input class="form-check-input" type="checkbox" disabled>
                                            {% endif %}
                                        </p>
                                        <p class="col card-text">M: 
                                            {% if menu.miercoles %}
                                                <input class="form-check-input" type="checkbox" checked disabled>
                                            {% else %}
                                                <input class="form-check-input" type="checkbox" disabled>
                                            {% endif %}
                                        </p>
                                        <p class="col card-text">J: 
                                            {% if menu.jueves %}
                                                <input class="form-check-input" type="checkbox" checked disabled>
                                            {% else %}
                                                <input class="form-check-input" type="checkbox" disabled>
                                            {% endif %}
                                        </p>
                                        <p class="col card-text">V: 
                                            {% if menu.viernes %}
                                                <input class="form-check-input" type="checkbox" checked disabled>
                                            {% else %}
                                                <input class="form-check-input" type="checkbox" disabled>
                                            {% endif %}
                                        </p>
                                        <p class="col card-text">S: 
                                            {% if menu.sabado %}
                                                <input class="form-check-input" type="checkbox" checked disabled>
                                            {% else %}
                                                <input class="form-check-input" type="checkbox" disabled>
                                            {% endif %}
                                        </p>
                                        <p class="col card-text">D: 
                                            {% if menu.domingo %}
                                                <input class="form-check-input" type="checkbox" checked disabled>
                                            {% else %}
                                                <input class="form-check-input" type="checkbox" disabled>
                                            {% endif %}
                                        </p>
                                    </div>
                                    <a href="{% url 'menus:editar_menu' menu.id %}" class="btn btn-outline-warning mt-4 me-3">
                                        <span>Editar</span>
                                    </a>
                                    <a href="{% url 'menus:eliminar_menu' menu.id %}" class="btn btn-outline-danger mt-4 me-3">
                                        <span>Eliminar</span>
                                    </a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
            {% else %}
                <p>No hay menús creados</p>
            {% endif %}
        </div>
        {% endif %}

    </div>
</main>
{% endblock  %}